spring:
  profiles:
    active: "dev"
---
spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name: findmax
server:
  port: 8080
  error:
    whitelabel:
      enabled=false:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs